CREATE TABLE user_shop (
Id INTEGER PRIMARY KEY AUTO_INCREMENT,
User_id INTEGER NOT NULL,
Shop_id INTEGER NOT NULL,
CONSTRAINT Shops_id 
	FOREIGN KEY (Shop_id)
	REFERENCES Shops (id)
	ON UPDATE CASCADE
	ON DELETE NO ACTION,
CONSTRAINT Users_id 
	FOREIGN KEY (User_id)
	REFERENCES Users (id)
	ON UPDATE CASCADE
	ON DELETE NO ACTION
)
;

CREATE TABLE `User_shop` (
  `id` int(11) NOT NULL,
  `User_id` int(11) NOT NULL,
  `Shop_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `User_shop`
  ADD PRIMARY KEY (`id`),
  ADD KEY `Shops_Shop_id` (`id`),
  ADD KEY `Users_User_id` (`id`);

ALTER TABLE `User_shop`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

ALTER TABLE `User_shop`
  ADD CONSTRAINT `Shops_id` FOREIGN KEY (`shop_id`) REFERENCES `Shops` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE,
  ADD CONSTRAINT `Users_id` FOREIGN KEY (`user_id`) REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE;


CREATE TABLE list (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
nimi VARCHAR(100) NOT NULL,
created_at timestamp NULL DEFAULT NULL,
updated_at timestamp NULL DEFAULT NULL,
usershops_id INTEGER UNSIGNED NOT NULL,
CONSTRAINT FK_usershops FOREIGN KEY (usershops_id)
	REFERENCES user_shops(id) 
	ON DELETE NO ACTION
	ON UPDATE CASCADE
)
;

CREATE TABLE product (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
nimi VARCHAR(100) NOT NULL,
valmistaja VARCHAR(60) DEFAULT '-',
koko DECIMAL DEFAULT NULL
);

CREATE TABLE product_list (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
list_id INTEGER NOT NULL,
product_id INTEGER NOT NULL,
CONSTRAINT FK_list FOREIGN KEY (list_id)
	REFERENCES list(id) 
	ON DELETE NO ACTION
	ON UPDATE CASCADE,
CONSTRAINT FK_product FOREIGN KEY (product_id)
	REFERENCES product(id) 
	ON DELETE NO ACTION
	ON UPDATE CASCADE
)
;
ALTER TABLE `listas` DROP FOREIGN KEY `FK_usershops`; ALTER TABLE `listas` ADD CONSTRAINT `FK_usershops` FOREIGN KEY (`usershops_id`) REFERENCES `taianoma_romeo`.`user_shops`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `product_lists` DROP FOREIGN KEY `FK_list`; ALTER TABLE `product_lists` ADD CONSTRAINT `FK_list` FOREIGN KEY (`list_id`) REFERENCES `taianoma_romeo`.`listas`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE `product_lists` DROP FOREIGN KEY `FK_product`; ALTER TABLE `product_lists` ADD CONSTRAINT `FK_product` FOREIGN KEY (`product_id`) REFERENCES `taianoma_romeo`.`products`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;